import { PlayerListType } from "@/component/pages/main/_parts/SquadSection";

/** api 통신 주소 */
export const url =
  process.env.NEXT_PUBLIC_APP_ENV === "dev" ? "http://localhost:9988" : "api~~";

/** 이름 목록 */
export const nameList: PlayerListType[] = [
  { name: "다은", sex: "여" },
  { name: "마이클", sex: "남" },
  { name: "명진", sex: "여" },
  { name: "미로", sex: "여" },
  { name: "민영", sex: "여" },
  // { name: "부찬", sex: "남" },
  { name: "상준", sex: "남" },
  { name: "성현", sex: "남" },
  { name: "승우", sex: "여" },
  { name: "승혁", sex: "남" },
  { name: "수진", sex: "여" },
  { name: "영재", sex: "남" },
  // { name: "윤경", sex: "여" },
  { name: "지혁", sex: "남" },
  { name: "주명", sex: "남" },
  { name: "주희", sex: "여" },
  { name: "정현", sex: "여" },
  { name: "종사", sex: "남" },
  { name: "재권", sex: "남" },
];

export const cardList = [
  {
    name: "연다은",
    nickName: "3분 슈퍼 조커",
    description: "교체로 들어가 활약 후 다시 교체해 나온다",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "마이클",
    nickName: "호주의 박지성",
    description: "지치지 않는 체력, 두유노 마이클?",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "이명진",
    nickName: "열정열쩡열정!",
    description: "열정 넘치는 플레이, 열정 넘치는 콜, 열정 넘치는 세레머니",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "미로",
    nickName: "푸릇 개근상",
    description: "가장 꾸준히 참석하고 있는 푸릇 중 1인, 무럭무럭 성장중이다",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "박민영",
    nickName: "푸릇푸릇 주장",
    description: "세상아 굴러라..!!",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  // {
  //   name: "김부찬",
  //   nickName: "푸릇푸릇 부코치",
  //   description: "※주의 : 푸릇함 속에 감춰진 실력은 절대 푸릇하지 않다",
  //   point1: "그건 제 잔상입니다만...",
  //   point2: "무야호...!",
  //   point3: "아무말아무말",
  // },
  {
    name: "김상준",
    nickName: "언젠가는 강인리",
    description: "날아라 슛돌이? 쿠당탕탕 맛도리",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "김성현",
    nickName: "헬창 범블비",
    description: "몸싸움 하지 마세요. 저에게 양보하세요, 스킨 푸드.",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "김승우",
    nickName: "공권력 행사",
    description: "공 이리내! 당신은 묵비권을...",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "이승혁",
    nickName: "푸르릇 아이브",
    description: "드리블도 디자인해주지...",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "박수진",
    nickName: "푸릇 김민재",
    description: "푸릇의 벽이 되고 싶은 소망이 있다",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "정영재",
    nickName: "푸딩크",
    description: "자신만의 역사를 쓴 후 은퇴, 푸릇푸릇에서 여유롭게 활동중이다",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  // {
  //   name: "이윤경",
  //   nickName: "푸릇푸릇 셀럽",
  //   description: "푸릇푸릇을 아는데 나를 모른다?!",
  //   point1: "그건 제 잔상입니다만...",
  //   point2: "무야호...!",
  //   point3: "아무말아무말",
  // },
  {
    name: "박지혁",
    nickName: "마스터 쉐프",
    description: "음... 간 좀 볼까?",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "윤주명",
    nickName: "푸릇 수호신",
    description: "1:1? 드루와... 드루와...",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "지주희",
    nickName: "전설의 포켓몬",
    description: "가끔씩 모습을 드러내며, 보기 힘든 전설의 포켓몬",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "박정현",
    nickName: "세니(공격모드)",
    description: "필드 위에서는 공격성과 공에 대한 집중력이 상승한다",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "김종사",
    nickName: "플랩 루터킹",
    description: "세미 프로,,, 아이해브어 드림",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
  {
    name: "차재권",
    nickName: "재즈 풋살러",
    description: "넌 전혀 풋살을 하고 있지 않아...",
    point1: "그건 제 잔상입니다만...",
    point2: "무야호...!",
    point3: "아무말아무말",
  },
];
